server:
  port: 8088
  servlet:
    context-path: /term
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/term?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: zcx88372565
    driver-class-name: com.mysql.cj.jdbc.Driver
